"""Adding New Car Table

Revision ID: 91711fc447cf
Revises: 6655f75b2b30
Create Date: 2021-04-14 21:43:27.819433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91711fc447cf'
down_revision = '6655f75b2b30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('car_make', sa.String(length=150), nullable=True),
    sa.Column('car_model', sa.String(length=150), nullable=True),
    sa.Column('car_year', sa.String(length=150), nullable=True),
    sa.Column('car_color', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
